#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pyudev
Version  : 0.24.0
Release  : 40
URL      : https://github.com/pyudev/pyudev/archive/v0.24.0/pyudev-0.24.0.tar.gz
Source0  : https://github.com/pyudev/pyudev/archive/v0.24.0/pyudev-0.24.0.tar.gz
Summary  : A libudev binding
Group    : Development/Tools
License  : LGPL-2.1
Requires: pyudev-license = %{version}-%{release}
Requires: pyudev-python = %{version}-%{release}
Requires: pyudev-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
######
pyudev
######
.. image:: https://secure.travis-ci.org/pyudev/pyudev.png?branch=develop
:target: http://travis-ci.org/pyudev/pyudev

%package license
Summary: license components for the pyudev package.
Group: Default

%description license
license components for the pyudev package.


%package python
Summary: python components for the pyudev package.
Group: Default
Requires: pyudev-python3 = %{version}-%{release}

%description python
python components for the pyudev package.


%package python3
Summary: python3 components for the pyudev package.
Group: Default
Requires: python3-core
Provides: pypi(pyudev)

%description python3
python3 components for the pyudev package.


%prep
%setup -q -n pyudev-0.24.0
cd %{_builddir}/pyudev-0.24.0
pushd ..
cp -a pyudev-0.24.0 buildavx2
cp -a pyudev-0.24.0 buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1672198184
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pyudev
cp %{_builddir}/pyudev-%{version}/COPYING %{buildroot}/usr/share/package-licenses/pyudev/545f380fb332eb41236596500913ff8d582e3ead
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pyudev/545f380fb332eb41236596500913ff8d582e3ead

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
